development: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  database: ci_dev
  username: root
  password: 12345678
  collation: utf8_general_ci
  variables:
    sql_mode: :default

test:
  <<: *base
  database: ci_test
  min_messages: WARNING
  
production:
  <<: *base
  database: ci_production
